### ISSUE TITLE
Usage and VB language Edition

### ISSUE THREAD

**Issue by u-riaz** [timfel/moss.rb#2]
Hi, 
Can you please help me to figure-out how to use your code? Means that how to provide input files, where to find results etc. 
Additionally, i want to check plagiarism of codes written in VB language. Can you provide more finer details how to add this feature in your repo. I had o look in conf/ , my questions is, only adding a file of keywords/tokens of some language would be necessary at all? how ?

best wishes.. Thanks

**Comment by timfel** [comment]
Sorry, I never spent the time with this it needed. This thing is unmaintained, and for my teaching I have been using the [Moss service](https://theory.stanford.edu/~aiken/moss/) directly. If you need Ruby code to do that, there's a Ruby gem: https://bitbucket.org/macite/moss-ruby

**Comment by u-riaz** [comment]
Thanks for your reply. 
Tim, actually I need MOSS' source code to-do some changes according to my requirements (special checks of VB) and then local installation. Unfortunately, I can't use Online Service directly. 
Can you help in this regard, do you know someone or link etc. who had implementation of MOSS?

**Comment by timfel** [comment]
Sorry, but I don't know anyone who has access to the MOSS code.
